### PR TITLE
fix to use Player.ReadyList (skip dedicated server)

### LINKED ISSUE #208: Fix playerlist command

### PR DESCRIPTION
**Pull request by TiBarification**
Closes #208

### CODE REVIEW

File: SCPDiscordPlugin/Utilities.cs [hunk 1]
```diff
@@ -93,9 +93,14 @@ public static bool TryGetPlayer(string userID, out Player pl)
...
-      foreach (Player player in Player.List)
+      foreach (Player player in Player.ReadyList)
       {
-        if (userID.Contains(player.GetParsedUserID()))
+				var parsedUserID = player.GetParsedUserID();
+				if (parsedUserID == null)
+				{
+					continue;
+				}
+				if (userID.Contains(parsedUserID))
```
Comment (KarlOfDuty) [inline SCPDiscordPlugin/Utilities.cs]: The whitespace here is tabs when it should be spaces.

**Review by KarlOfDuty — CHANGES_REQUESTED** [review]

**Review by KarlOfDuty — APPROVED** [review]
